version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Build Project
          command: npm build

  lint:
    docker:
      - image: circleci/node:current
    steps:
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
      - run:
          name: lint
          command: npm lint

  test:
    docker:
      - image: circleci/node:latest
    steps:
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
      - run:
          name: Tests
          command: npm test-with-coverage
      - store_test_results:
          path: coverage
        # Save workspace for subsequent (test)
      - persist_to_workspace:
          root: .
          paths:
            - .

  publish_coverage:
    docker:
      - image: circleci/node:latest
    steps:
      # Reuse the workspace from the build job
      - attach_workspace:
          at: .
      - run:
          name: Publish coverage
          command: yarn codecov -f coverage/*.json

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish_coverage:
          requires:
            - test
