version: 2.1

orbs:
  node: circleci/node@3.0.0

jobs:
  build:
    docker:
      - image: circleci/node:14
    parallelism: 1

    steps:
      - checkout
      - node/install-packages:
          cache-path: node_modules
          override-ci-command: yarn --frozen-lockfile

      # Save workspace for subsequent (test)
      - persist_to_workspace:
        root: .
        paths:
          - .

      - run:
          name: Build Project
          command: yarn build

  test:
    docker:
      - image: circleci/node:14
    parallelism: 1

    steps:
      # Reuse the workspace from the build job
      - attach_workspace:
          at: .

      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-

      - run:
          name: Tests
          command: yarn test-with-coverage
      - store_test_results:
          path: coverage

  publish_coverage:
    docker:
      - image: circleci/node:14
    parallelism: 1

    steps:
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-

      - run:
          name: Publish coverage
          command: yarn codecov -f coverage/*.json

workflows:
  version: 2
  build_test_publish_coverage:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish_coverage:
          requires:
            - test
