version: 2.1
# orbs:
#   codecov: codecov/codecov@1.0.4
jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Update-npm
          command: 'sudo npm install -g npm@5'
      - restore_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Build Project
          command: yarn build
      - run:
          name: Tests
          command: yarn test-with-coverage
      - run:
          name: Publish coverage
          command: yarn codecov -f coverage/*.json
