version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    parallelism: 1

    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-

      - run:
          name: Install dependencies
          command: yarn --frozen-lockfile --cache-folder ~/.cache/yarn

      - save_cache:
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Build Project
          command: yarn build

  test:
    docker:
      - image: circleci/node:14
    parallelism: 1

    steps:
      - restore_cache:
          keys:
            - ~/.cache/yarn/yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - ~/.cache/yarn/yarn-packages-v1-{{ .Branch }}-
            - ~/.cache/yarn/yarn-packages-v1-

      - run:
          name: Tests
          command: yarn test-with-coverage
      - store_test_results:
          path: coverage

  publish_coverage:
    docker:
      - image: circleci/node:14
    parallelism: 1

    steps:
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-

      - run:
          name: Publish coverage
          command: yarn codecov -f coverage/*.json

workflows:
  version: 2
  build_test_publish_coverage:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish_coverage:
          requires:
            - test
