version: 2.1
# orbs:
#   codecov: codecov/codecov@1.0.4
  build:
    docker:
      - image: circleci/node:10
    paralelism: 4
    steps:
      - checkout
      - run:
          name: Update-npm
          command: "sudo npm install -g npm@5"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build Project
          command: npm run build
      # - codecov/upload:
      #     flags: backend,unittest
      # - run: npm install codecov -g
      # - run: codecov --token=CODECOV_TOKEN
      # - codecov/upload:
      #     file: coverage/*.json
      #     flags: frontend