version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    parallelism: 1

    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Build Project
          command: yarn build

  test:
    docker:
      - image: circleci/node:14
    parallelism: 4

    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Tests
          command: yarn test-with-coverage
      - store_test_results:
          destination: coverage

  publish_coverage:
    docker:
      - image: circleci/node:14
    parallelism: 1

    steps:
      - run:
          name: Publish coverage
          command: yarn codecov -f coverage/*.json

workflows:
  version: 2
  build_test_publish_coverage:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish_coverage:
          requires:
            - test
