version: 2.1

orbs:
  ruby: circleci/ruby@1.0

jobs:
  build:
    working_directory: ~/corde
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          key: v1-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Build Project
          command: yarn build

  lint:
    working_directory: ~/corde
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: lint
          command: yarn lint

  unit-node-12:
    working_directory: ~/corde
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Tests
          command: yarn test-coverage
      - store_test_results:
          path: coverage
        # Save workspace for subsequent (test)
      - persist_to_workspace:
          root: .
          paths:
            - .

  unit-node-14:
    working_directory: ~/corde
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Tests
          command: yarn test-with-coverage
      - store_test_results:
          path: coverage
        # Save workspace for subsequent (test)
      - persist_to_workspace:
          root: .
          paths:
            - .

  publish_coverage:
    working_directory: ~/corde
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn
      # Reuse the workspace from the build job
      - attach_workspace:
          at: .
      - run:
          name: Publish coverage
          command: yarn codecov -f coverage/*.json

  publish_website:
    working_directory: ~/corde
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Deploy Corde website if needed
          command: sh ./.circleci/website.sh

workflows:
  version: 2

  build-and-test:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages

      - lint:
          requries:
            - build
          filters:
            branches:
              ignore: gh-pages

      - unit-node-12:
          requires:
            - build
          filters:
            branches:
              ignore: gh-pages

      - unit-node-14:
          requires:
            - build
          filters:
            branches:
              ignore: gh-pages

      - publish_coverage:
          requires:
            - unit-node-12
            - unit-node-14
          filters:
            branches:
              ignore: gh-pages

  website-build-deploy:
    jobs:
      - publish_website:
          filters:
            branches:
              only: master # Restrict website deploy to only master branch
