version: 2.1

orbs:
  node: circleci/node@3.0.0

jobs:
  build:
    docker:
      - image: circleci/node:14
    parallelism: 1

    executor: node/default
    steps:
      - checkout
      - node/install-npm
      - node/install-packages:
          app-dir: ~/corde
          cache-path: node_modules
          override-ci-command: npm i

      # Save workspace for subsequent (test)
      - persist_to_workspace:
        root: .
        paths:
          - .

      - run:
          name: Build Project
          command: npm run build

  test:
    docker:
      - image: circleci/node:14
    parallelism: 1

    steps:
      # Reuse the workspace from the build job
      - attach_workspace:
          at: .

      - run:
          name: Tests
          command: npm run test-with-coverage
      - store_test_results:
          path: coverage

  publish_coverage:
    docker:
      - image: circleci/node:14
    parallelism: 1

    steps:
      # Reuse the workspace from the build job
      - attach_workspace:
        at: .

      - run:
          name: Publish coverage
          command: npm run codecov -f coverage/*.json

workflows:
  version: 2
  build_test_publish_coverage:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish_coverage:
          requires:
            - test
