version: 2.1

orbs:
  node: circleci/node@3.0.1

jobs:
  build:
    docker:
      - image: circleci/node:14

    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          cache-path: ~/corde/node_modules
          override-ci-command: yarn install

      - run: yarn test

      # Save workspace for subsequent (test)
      - persist_to_workspace:
          root: .
          paths:
            - .

      - run:
          name: Build Project
          command: yarn build

  test:
    executor: node/default

    steps:
      # Reuse the workspace from the build job
      - attach_workspace:
          at: .

      - run:
          name: Tests
          command: yarn test-with-coverage

      - store_test_results:
          path: coverage

  publish_coverage:
    executor: node/default

    steps:
      # Reuse the workspace from the build job
      - attach_workspace:
          at: .

      - run:
          name: Publish coverage
          command: yarn codecov -f coverage/*.json

workflows:
  version: 2
  build_test_publish_coverage:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish_coverage:
          requires:
            - test
