version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14

    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Build Project
          command: yarn build

      - run:
          name: Tests
          command: yarn test-with-coverage

      - run:
          name: Publish coverage
          command: yarn codecov -f coverage/*.json

      - store_test_results:
          path: coverage/*.xml
