version: 1
update_configs:
  # Update web app
  - package_manager: 'javascript'
    update_schedule: 'daily'
    directory: './'
    automerged_updates:
      - match:
          dependency_type: 'all'
          update_type: 'all'
  - package_manager: "javascript"
    directory: "./examples/javascript"
    update_schedule: "daily"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
  - package_manager: "javascript"
    directory: "./examples/typescript"
    update_schedule: "daily"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
