version: 1
update_configs:
  # Update web app
  - package_manager: 'javascript'
    update_schedule: 'daily'
    directory: './'
    automerged_updates:
      - match:
          dependency_type: 'all'
          update_type: 'all'
