# This is a basic workflow to help you get started with Actions

name: e2e-test

# Controls when the acti

on: [push]

jobs:
  e2e-test-linux:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: yarn-and-build-cache

        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-build-

      - name: Install modules
        run: yarn

      - name: Build
        run: yarn build

      - name: Run tests
        run: yarn e2e
